version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance  # Persist database
    environment:
      FLASK_APP: "app.py"
      FLASK_DEBUG: "1"
      SECRET_KEY: "your-secret-key"